added parallel env

diff --git a/bin/get-java b/bin/get-java
--- a/bin/get-java
+++ b/bin/get-java
@@ -121,6 +121,74 @@ function get_debian_codename() {
     local -r result=$(string_strip_prefix "$version_codename_line" "VERSION_CODENAME=")
     echo "$result"
 }
+function extract() {
+    if file_exists "$1"; then
+        if [[ "$2" == "" ]]; then
+            case "$1" in
+            *.rar)
+                rar x "$1" "${1%.rar}"/
+                if ! os_command_is_available "rar"; then
+                    log_error "rar is not available. existing..."
+                    exit 1
+                fi
+                ;;
+            *.tar.bz2) mkdir -p "${1%.tar.bz2}" && tar xjf "$1" -C "${1%.tar.bz2}"/ ;;
+            *.tar.gz) mkdir -p "${1%.tar.gz}" && tar xzf "$1" -C "${1%.tar.gz}"/ ;;
+            *.tar.xz) mkdir -p "${1%.tar.xz}" && tar xf "$1" -C "${1%.tar.xz}"/ ;;
+            *.tar) mkdir -p "${1%.tar}" && tar xf "$1" -C "${1%.tar}"/ ;;
+            *.tbz2) mkdir -p "${1%.tbz2}" && tar xjf "$1" -C "${1%.tbz2}"/ ;;
+            *.tgz) mkdir -p "${1%.tgz}" && tar xzf "$1" -C "${1%.tgz}"/ ;;
+
+            *.zip)
+                if ! os_command_is_available "unzip"; then
+                    log_error "unzip is not available. existing..."
+                    exit 1
+                fi
+                unzip -oq "$1" -d "${1%.zip}"/
+                ;;
+            # *.zip) unzip "$1" -d "${1%.zip}"/ ;;
+            *.7z) 7za e "$1" -o"${1%.7z}"/ ;;
+            *) log_error "$1 cannot be extracted." ;;
+            esac
+        else
+            case "$1" in
+            *.rar)
+                if ! os_command_is_available "rar"; then
+                    log_error "rar is not available. existing..."
+                    exit 1
+                fi
+                rar x "$1" "$2"
+                ;;
+            *.tar.bz2) mkdir -p "$2" && tar xjf "$1" -C "$2" ;;
+            *.tar.gz) mkdir -p "$2" && tar xzf "$1" -C "$2" ;;
+            *.tar.xz) mkdir -p "$2" && tar xf "$1" -C "$2" ;;
+            *.tar) mkdir -p "$2" && tar xf "$1" -C "$2" ;;
+            *.tbz2) mkdir -p "$2" && tar xjf "$1" -C "$2" ;;
+            *.tgz) mkdir -p "$2" && tar xzf "$1" -C "$2" ;;
+            *.zip)
+                if ! os_command_is_available "unzip"; then
+                    log_error "unzip is not available. existing..."
+                    exit 1
+                fi
+                unzip -oq "$1" -d "$2"
+                ;;
+            # *.zip) unzip "$1" -d "$2" ;;
+            *.7z) 7z e "$1" -o"$2"/ ;;
+            *) log_error "$1 cannot be extracted." ;;
+            esac
+        fi
+    else
+        log_error "$1 cannot be extracted."
+    fi
+}
+function get_file_name() {
+    local -r target="$1"
+    echo "${target##*/}"
+}
+function get_file_dir() {
+    local -r target="$1"
+    echo "${target%/*}"
+}
 function assert_not_empty() {
     local -r arg_name="$1"
     local -r arg_value="$2"
@@ -316,91 +384,3 @@ function init() {
         env_parallel --init
     fi
 }
-
-function help() {
-    echo
-    echo "Usage: [$(basename "$0")] [OPTIONAL FLAG] [COMMAND | COMMAND <FLAG> <ARG>]"
-    echo
-    echo
-    echo -e "[Synopsis]:\ta collection of file/folder operation helpers"
-    echo
-    echo -e "  r-md5\t\t\tRecursively generate md5 hashes in target dirs ."
-    echo -e "  [flag|optional]\t--dupes \tonly list duplicates.[DEFAULT: 'false']"
-    echo -e "  [flag|optional]\t--output <arg> \tTarget to store the list in.[DEFAULT: 'mdsums.list']"
-    echo -e "  [flag(s)|optional]\t--dir <arg> \tDirectories to search.[DEFAULT: '$PWD']"
-    echo
-    echo -e "  dedup\t\t\tRecursively finds duplicate files in directory by comparing them"
-    echo -e "\t\t\twith files in an origin directory ."
-    echo -e "  \t\t\tIt does not delete duplicates in origin directory"
-    echo -e "  [flag|optional]\t--output <arg> \tTarget to store the list of deleted files in."
-    echo -e "  [flag]\t\t--origin <arg> \torigin directory."
-    echo -e "  [flag(s)]\t\t--target <arg> \tdirectories to be deduplicated."
-    echo
-    echo
-    echo "Optional Flags:"
-    echo
-    echo -e "  --init\t\tinitializes and installs dependancies for $(basename "$0")"
-    echo -e "  --update\t\tupdates $(basename "$0") to the letest version at master branch."
-    echo
-    echo "Example:"
-    echo
-    echo "  sudo $(basename "$0") --init "
-    echo
-}
-
-function update() {
-    local -r url="https://raw.githubusercontent.com/da-moon/core-utils/master/bin/$(basename "$0")"
-    local -r install_location=$(whereis "$(basename "$0")" | grep -E -o "$(basename "$0").*" | cut -f2- -d: | tr -s ' ' | cut -d ' ' -f2)
-    log_info "updating $(basename "$0") located at $install_location"
-    if [ ! -w "$install_location" ]; then
-        log_info "needs sudo for updating file at $install_location"
-        confirm_sudo
-        [ "$(whoami)" = root ] || exec sudo "$0" "$@"
-    fi
-    log_info "removing old file at $install_location"
-    rm "$install_location"
-    log_info "downloading $url"
-    wget -q -O "$install_location" "$url"
-    log_info "setting $install_location as executable"
-    chmod +x "$install_location"
-}
-function main() {
-    if [[ $# == 0 ]]; then
-        help
-        exit
-    fi
-    while [[ $# -gt 0 ]]; do
-        local key="$1"
-
-        case "$key" in
-        --init)
-            log_info "initializing futils"
-            init
-            shift
-            ;;
-        --update)
-            update
-            shift
-            ;;
-        --help)
-            help
-            exit
-            ;;
-        *)
-            log_error "Unrecognized option: $key"
-            echo -e "\t\t\t\tRun '$(basename "$0") --help' for a list of known subcommands." >&2
-            exit 1
-            ;;
-        esac
-        shift
-    done
-}
-if [ -n ${BASH_SOURCE+x} ]; then
-    main "${@}"
-    exit $?
-fi
-if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
-else
-    main "${@}"
-    exit $?
-fi
