added get-hashi and run-sc and updated readme

diff --git a/bin/get-hashi b/bin/get-hashi
--- a/bin/get-hashi
+++ b/bin/get-hashi
@@ -88,7 +88,7 @@ function is_pkg_installed() {
     dpkg -s "$pkg" 2>/dev/null | grep ^Status | grep -q installed
 }
 function confirm_sudo() {
-    if ! $(is_root); then
+    if ! is_root; then
         log_error "needs root permission to run.exiting..."
         exit 1
     fi
@@ -98,7 +98,7 @@ function confirm_sudo() {
         apt-get -qq update &&
             DEBIAN_FRONTEND=noninteractive apt-get install -qqy apt-utils
     fi
-    if ! $(has_sudo); then
+    if ! has_sudo; then
         log_info "sudo is not available ... installing now"
         apt-get -qq update &&
             DEBIAN_FRONTEND=noninteractive apt-get install -qqy "$target"
@@ -117,7 +117,7 @@ function apt_cleanup() {
 }
 function filter_installed() {
     local -r deps=("$@")
-    local -r raw_list=$(dpkg -s ${deps[@]} 2>&1)
+    local -r raw_list=$(dpkg -s "${deps[@]}" 2>&1)
     local -r filtered=$(echo "${raw_list}" | grep -E "dpkg-query: package")
     local -r trimmed=$(echo "${filtered}" | sed -n "s,[^']*'\([^']*\).*,\1,p")
     echo "$trimmed"
@@ -198,14 +198,127 @@ function install_deps() {
         apt_cleanup
     fi
 }
-function fast_apt() {
-    log_info "running fast-apt ..."
-    apt_cleanup
+
+function extract() {
+    if file_exists "$1"; then
+        if [[ "$2" == "" ]]; then
+            case "$1" in
+            *.rar)
+                rar x "$1" "${1%.rar}"/
+                if ! os_command_is_available "rar"; then
+                    log_error "rar is not available. existing..."
+                    exit 1
+                fi
+                ;;
+            *.tar.bz2) mkdir -p "${1%.tar.bz2}" && tar xjf "$1" -C "${1%.tar.bz2}"/ ;;
+            *.tar.gz) mkdir -p "${1%.tar.gz}" && tar xzf "$1" -C "${1%.tar.gz}"/ ;;
+            *.tar.xz) mkdir -p "${1%.tar.xz}" && tar xf "$1" -C "${1%.tar.xz}"/ ;;
+            *.tar) mkdir -p "${1%.tar}" && tar xf "$1" -C "${1%.tar}"/ ;;
+            *.tbz2) mkdir -p "${1%.tbz2}" && tar xjf "$1" -C "${1%.tbz2}"/ ;;
+            *.tgz) mkdir -p "${1%.tgz}" && tar xzf "$1" -C "${1%.tgz}"/ ;;
+
+            *.zip)
+                if ! os_command_is_available "unzip"; then
+                    log_error "unzip is not available. existing..."
+                    exit 1
+                fi
+                unzip -oq "$1" -d "${1%.zip}"/
+                ;;
+            # *.zip) unzip "$1" -d "${1%.zip}"/ ;;
+            *.7z) 7za e "$1" -o"${1%.7z}"/ ;;
+            *) log_error "$1 cannot be extracted." ;;
+            esac
+        else
+            case "$1" in
+            *.rar)
+                if ! os_command_is_available "rar"; then
+                    log_error "rar is not available. existing..."
+                    exit 1
+                fi
+                rar x "$1" "$2"
+                ;;
+            *.tar.bz2) mkdir -p "$2" && tar xjf "$1" -C "$2" ;;
+            *.tar.gz) mkdir -p "$2" && tar xzf "$1" -C "$2" ;;
+            *.tar.xz) mkdir -p "$2" && tar xf "$1" -C "$2" ;;
+            *.tar) mkdir -p "$2" && tar xf "$1" -C "$2" ;;
+            *.tbz2) mkdir -p "$2" && tar xjf "$1" -C "$2" ;;
+            *.tgz) mkdir -p "$2" && tar xzf "$1" -C "$2" ;;
+            *.zip)
+                if ! os_command_is_available "unzip"; then
+                    log_error "unzip is not available. existing..."
+                    exit 1
+                fi
+                unzip -oq "$1" -d "$2"
+                ;;
+            # *.zip) unzip "$1" -d "$2" ;;
+            *.7z) 7z e "$1" -o"$2"/ ;;
+            *) log_error "$1 cannot be extracted." ;;
+            esac
+        fi
+    else
+        log_error "$1 cannot be extracted."
+    fi
+}
+function get_file_name() {
+    local -r target="$1"
+    echo "${target##*/}"
+}
+function get_file_dir() {
+    local -r target="$1"
+    echo "${target%/*}"
+}
+function assert_not_empty() {
+    local -r arg_name="$1"
+    local -r arg_value="$2"
+    local -r reason="$3"
+    if [[ -z "$arg_value" ]]; then
+        log_error "'$arg_name' cannot be empty. $reason"
+        exit 1
+    fi
+}
+function get_hashi_latest_version() {
+    if [[ $# != 1 ]]; then
+        echo
+        echo "desc : gets latest version of a hashicorp software"
+        echo
+        echo "method usage: get_hashi_latest_version [software name]"
+        echo
+        exit 1
+    fi
+    assert_not_empty "get_hashi_latest_version" "$1" "user input is needed"
+    local -r reply=$(curl -sL "https://releases.hashicorp.com/${1}/index.json")
+    local -r versions=$(echo "$reply" | jq -r '.versions[].version')
+    local -r sorted=$(echo "$versions" | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n)
+    local -r trimmed=$(echo "$sorted" | grep -E -v 'ent|rc|beta')
+    local -r latest=$(echo "$trimmed" | tail -1)
+    echo "$latest"
+}
+function get_hashi() {
+    if [[ $# == 0 ]]; then
+        echo
+        echo "desc : downloads and installs lastes hashicorp software"
+        echo
+        echo "method usage: get_hashi [list of software name]"
+        echo
+        exit 1
+    fi
     [ "$(whoami)" = root ] || exec sudo "$0" "$@"
-    apt-get -y --print-uris $@ | grep -o -E "(ht|f)t(p|ps)://[^\']+" >>/tmp/apt-fast.list
-    if echo "$@" | grep -q "upgrade\|install\|dist-upgrade"; then
-        install_deps
-        pushd "/var/cache/apt/archives/" >/dev/null 2>&1
+    local -r packages=("$@")
+    local -r download_list="/tmp/hashistack.list"
+    rm -f "${download_list}"
+    for name in "${packages[@]}"; do
+        log_info "adding ${name}"
+        rm -f "/tmp/${name}"*
+        local version
+        local url
+        version=$(get_hashi_latest_version "${name}")
+        log_info "adding ${name} version ${version} to download-list ${download_list}"
+        url="https://releases.hashicorp.com/${name}/${version}/${name}_${version}_linux_amd64.zip"
+        echo "${url}" >>"${download_list}"
+        echo " out=${name}.zip" >>"${download_list}"
+    done
+    if file_exists "${download_list}"; then
+        pushd "/tmp/" >/dev/null 2>&1
         aria2c \
             -j 16 \
             --continue=true \
@@ -213,64 +326,36 @@ function fast_apt() {
             --optimize-concurrent-downloads \
             --connect-timeout=600 \
             --timeout=600 \
-            --input-file=/tmp/apt-fast.list
+            --input-file="${download_list}"
         [[ "$?" != 0 ]] && popd
         popd >/dev/null 2>&1
-        apt-get "$@" -y
-        apt_cleanup
-    else
-        apt-get "$@"
     fi
-}
-function help() {
-    echo
-    echo "Usage: [fast-apt] [OPTIONAL ARG] [COMMAND | COMMAND <FLAG> <ARG>]"
-    echo
-    echo
-    echo -e "[Synopsis]:\twrapper around apt-get which uses aria2 to download packages"
-    echo -e "\t\twhen running 'install' 'upgrade' and 'dist-upgrade'."
-    echo -e "\t\tin other cases, it just passes the command to apt-get"
-    echo
-    echo
-    echo "Optional Flags:"
-    echo
-    echo -e "  --init\t\tinitializes and installs dependancies."
-    echo
-    echo "Example:"
-    echo
-    echo "  sudo fast-apt --init "
-    echo
-    echo "  sudo fast-apt \\"
-    echo "      install -q nano"
-    echo
-}
-function main() {
-    if [[ $# == 0 ]]; then
-        help
-        exit
-    fi
-    while [[ $# -gt 0 ]]; do
-        local key="$1"
 
-        case "$key" in
-        --init)
-            shift
-            log_info "initializing base packages"
-            install_deps
-            exit
-            ;;
-        *)
-            fast_apt "${@}"
-            exit $?
-            ;;
-        esac
-        shift
+    local -r install_dir="/usr/bin/"
+    for name in "${packages[@]}"; do
+        extract "/tmp/${name}.zip" "$install_dir"
+        mkdir -p "/etc/${name}/" "/var/${name}/"
+        mkdir -p "/etc/${name}/" "/var/${name}/"
+        chmod -R 0600 "/etc/${name}/" "/var/${name}/"
+        chmod 0750 "/usr/bin/${name}"
+        chown "${USER}:${USER}" "/usr/bin/${name}"
+        if [[ "$name" == "vault" ]]; then
+            setcap cap_ipc_lock=+ep /usr/bin/vault
+        fi
+        chmod +x "${install_dir}/${name}"
+        rm "/tmp/${name}.zip"
+        # confirming install was successful
+        $name --version >/dev/null
     done
 }
-
 if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
-    export -f fast_apt
+    export -f get_hashi
 else
-    main "${@}"
-    exit $?
+    install_deps
+    stack=("vault" "consul" "nomad" "terraform" "packer")
+    if [[ "$#" != 0 ]]; then
+        stack=("${@}")
+    fi
+    log_info "install targets ${stack[*]}"
+    get_hashi "${stack[@]}"
 fi
