Update stream-dl

diff --git a/bin/stream-dl b/bin/stream-dl
--- a/bin/stream-dl
+++ b/bin/stream-dl
@@ -5,18 +5,120 @@ set -o errexit
 set -o nounset
 set -o pipefail
 export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-function os_command_is_available() {
-    local name
-    name="$1"
-    command -v "$name" >/dev/null
+function is_root() {
+    [ "$EUID" -eq 0 ]
+}
+function string_colorify() {
+    local -r input="$2"
+    # checking for colour availablity
+    ncolors=$(tput colors)
+    if [[ $ncolors -ge 8 ]]; then
+        local -r color_code="$1"
+        echo -e "\e[1m\e[$color_code"m"$input\e[0m"
+    else
+        echo -e "$input"
+    fi
+}
+function string_blue() {
+    local -r color_code="34"
+    local -r input="$1"
+    echo -e "$(string_colorify "${color_code}" "${input}")"
+}
+function string_yellow() {
+    local -r color_code="93"
+    local -r input="$1"
+    echo -e "$(string_colorify "${color_code}" "${input}")"
+}
+function string_green() {
+    local -r color_code="32"
+    local -r input="$1"
+    echo -e "$(string_colorify "${color_code}" "${input}")"
+}
+function string_red() {
+    local -r color_code="31"
+    local -r input="$1"
+    echo -e "$(string_colorify "${color_code}" "${input}")"
+}
+function log() {
+    local -r level="$1"
+    local -r message="$2"
+    local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+    local -r script_name="$(basename "$0")"
+    local color
+    case "$level" in
+    INFO)
+        color="string_green"
+        ;;
+    WARN)
+        color="string_yellow"
+        ;;
+    ERROR)
+        color="string_red"
+        ;;
+    esac
+    echo >&2 -e "$(${color} "${timestamp} [${level}] ==>") $(string_blue "[$script_name]") ${message}"
+
+}
+function log_info() {
+    local -r message="$1"
+    log "INFO" "$message"
+}
+function log_warn() {
+    local -r message="$1"
+    log "WARN" "$message"
+}
+function log_error() {
+    local -r message="$1"
+    log "ERROR" "$message"
 }
 function file_exists() {
     local -r file="$1"
     [[ -f "$file" ]]
 }
-
-function has_apt() {
-    os_command_is_available "apt"
+function os_command_is_available() {
+    local name
+    name="$1"
+    command -v "$name" >/dev/null
+}
+function has_sudo() {
+    os_command_is_available "sudo"
+}
+function is_pkg_installed() {
+    local -r pkg="$1"
+    dpkg -s "$pkg" 2>/dev/null | grep ^Status | grep -q installed
+}
+function confirm_sudo() {
+    if ! is_root; then
+        log_error "needs root permission to run.exiting..."
+        exit 1
+    fi
+    local target="sudo"
+    if ! is_pkg_installed "apt-utils"; then
+        log_info "apt-utils is not available ... installing now"
+        apt-get -qq update &&
+            DEBIAN_FRONTEND=noninteractive apt-get install -qqy apt-utils
+    fi
+    if ! has_sudo; then
+        log_info "sudo is not available ... installing now"
+        apt-get -qq update &&
+            DEBIAN_FRONTEND=noninteractive apt-get install -qqy "$target"
+    fi
+}
+function array_split() {
+    local -r separator="$1"
+    local -r str="$2"
+    local -a ary=()
+    IFS="$separator" read -ra ary <<<"$str"
+    echo "${ary[@]}"
+}
+function apt_cleanup() {
+    confirm_sudo
+    if file_exists "/tmp/apt-fast.list"; then
+        sudo rm /tmp/apt-fast.list
+    fi
+    sudo apt-get clean
+    sudo rm -rf /var/lib/apt/lists/*
+    sudo rm -rf /var/cache/apt/archives/*
 }
 function get_debian_codename() {
     local -r os_release=$(cat /etc/os-release)
@@ -30,25 +132,34 @@ function init() {
         exit 1
     fi
     if ! os_command_is_available "wget"; then
+        confirm_sudo
         echo "wget not found. installing ..."
         sudo apt-get update -qq && sudo apt-get install -yqq wget
+        apt_cleanup
     fi
     if ! os_command_is_available "aria2c"; then
+        confirm_sudo
         echo "aria2 not found. installing ..."
         sudo apt-get update -qq && sudo apt-get install -yqq aria2
+        apt_cleanup
     fi
     if ! os_command_is_available "curl"; then
+        confirm_sudo
         echo "curl not found. installing ..."
         sudo apt-get update -qq && sudo apt-get install -yqq curl
+        apt_cleanup
     fi
     if ! os_command_is_available "ffmpeg"; then
+        confirm_sudo
         echo "ffmpeg not found. installing ..."
         sudo apt-get update -qq && sudo apt-get install -yqq apt-transport-https
         curl -fsSL https://mkvtoolnix.download/gpg-pub-moritzbunkus.txt | sudo apt-key add -
         echo "deb https://mkvtoolnix.download/debian/ $(get_debian_codename) main" | sudo tee /etc/apt/sources.list.d/mkvtoolnix.download.list
         sudo apt-get update -qq && sudo apt-get install -yqq mkvtoolnix ffmpeg
+        apt_cleanup
     fi
     if ! os_command_is_available "ffmpeg-bar"; then
+        confirm_sudo
         echo "ffmpeg-bar not found. installing ..."
         if ! os_command_is_available "npm"; then
             echo "npm not found. installing ..."
@@ -59,6 +170,7 @@ function init() {
             sudo apt-get update -qq && sudo apt-get install -yqq nodejs yarn
         fi
         sudo npm install --global ffmpeg-progressbar-cli
+        apt_cleanup
     fi
 }
 function m3u8_downloader() {
